[local]
localhost

[mongodb]
mongodb.devops90.online

[redis]
redis.devops90.online

[mysql]
mysql.devops90.online

[rabbitmq]
rabbitmq.devops90.online

[catalogue]
catalogue.devops90.online

[user]
user.devops90.online

[cart]
cart.devops90.online

[shipping]
shipping.devops90.online

[payment]
payment.devops90.online

[frontend]
frontend.devops90.online
